from v1.generate_contract_pdf import generate_contract_pdf

print(
    generate_contract_pdf(
        contract_id="test1",
        company_name="Test Company",
        company_address="Bennelong Point, Sydney NSW 2000",
        date="09/11/2023",
        title="Mr",
        location_name="Sydney",
        farm_name="Opera House",
        first_name="Gildong",
        last_name="Hong",
        english_name="James",
        gender="male",
        birth_date="01/01/1990",
        cell_phone="0412 345 678",
        email="test@test.com",
        address="Bennelong Point, Sydney NSW 2000",
        tax_file_number="123 456 789",
        visa_grant_number="2009123456789",
        visa_expiry_date="01/01/2023",
        nationality="Korea, Republic",
        passport_number="M12345678",
        emergency_contact_name="John Watson",
        emergency_contact_cell_phone="0412 345 678",
        fund_name="Rest Super",
        member_number="123456789",
        bank_name="Sydney Bank",
        account_name="Gil Dong Hong",
        bsb="123 456",
        account_number="123456789",
        pre_existing_medical_condition="N",
        taking_medication="Y",
        recent_surgery="N",
        recent_injury="Y",
        job_related_limitation="N",
        job_stress="Y",
        mental_counseling="N",
        aware_of_eap="Y",
        aware_of_safety_policy="N",
        first_aid_training="Y",
        safety_reporting_comfort="N",
        bee_sting="Y",
        epilepsy="N",
        diabetes="Y",
        pregnant="N",
        high_blood_pressure="Y",
        other="chronic headaches",
        extra_disclosure="I suffer from chronic headaches, so I have to take medication every day.",
    )
)
